[[constraint]]
  name = "github.com/fatih/color"
  version = "1.7.0"

[[constraint]]
  name = "github.com/go-chi/chi"
  version = "4.0.2"

[[constraint]]
  name = "github.com/gocolly/colly"
  version = "1.2.0"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/lib/pq"
  version = "1.1.1"
